package pize.graphics.gl

import org.lwjgl.opengl.GL11

enum class Filter(val GL: Int) {
    NEAREST_MIPMAP_NEAREST(GL11.GL_NEAREST_MIPMAP_NEAREST),
    LINEAR_MIPMAP_NEAREST(GL11.GL_LINEAR_MIPMAP_NEAREST),
    NEAREST_MIPMAP_LINEAR(GL11.GL_NEAREST_MIPMAP_LINEAR),
    LINEAR_MIPMAP_LINEAR(GL11.GL_LINEAR_MIPMAP_LINEAR),
    NEAREST(GL11.GL_NEAREST),
    LINEAR(GL11.GL_LINEAR)
}
