package pize.graphics.gl

import org.lwjgl.opengl.GL11
import org.lwjgl.opengl.GL13
import org.lwjgl.opengl.GL14

enum class Hint(val GL: Int) {
    FOG_HINT(GL11.GL_FOG_HINT),
    GENERATE_MIPMAP_HINT(GL14.GL_GENERATE_MIPMAP_HINT),
    LINE_SMOOTH_HINT(GL11.GL_LINE_SMOOTH_HINT),
    PERSPECTIVE_CORRECTION_HINT(GL11.GL_PERSPECTIVE_CORRECTION_HINT),
    POINT_SMOOTH_HINT(GL11.GL_POINT_SMOOTH_HINT),
    POLYGON_SMOOTH_HINT(GL11.GL_POLYGON_SMOOTH_HINT),
    TEXTURE_COMPRESSION_HINT(GL13.GL_TEXTURE_COMPRESSION_HINT)
}